import { Open_Sans } from "next/font/google";
import "./globals.css";
import InfoRibbon from "./(components)/InfoRibbon";
import Navbar from "./(components)/Navbar";
import Footer from "./(components)/Footer";
import ScrollUp from "./(components)/ScrollUp";
import AuthProvider from "./(components)/AuthProvider";

const openSans = Open_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AYICC Zimbabwe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <AuthProvider>
      <body className={`${openSans.variable} antialiased`}>
        <InfoRibbon />
        <Navbar />
        {children}
        <Footer />
        <ScrollUp/>
      </body>
    </AuthProvider>
    </html>
  );
}
