import { Open_Sans } from "next/font/google";
import "./globals.css";
import InfoRibbon from "./(components)/InfoRibbon";
import Navbar from "./(components)/Navbar";
import Footer from "./(components)/Footer";

const openSans = Open_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ayicc Zimbabwe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} antialiased`}>
      <InfoRibbon/>
      <Navbar/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
